name: 'Merge Feature Branch'

on:
  workflow_dispatch:
    inputs:
      release_branch:
        description: 'Select branch to merge changes into'
        required: true
        type: choice
        options:
          - 'master'
          - 'release/v1.1'
          - 'release/v1.0'
      feature_branch:
        description: 'Feature branch'
        required: true
        type: string
      is_a_prerelease:
        description: 'Is this a prerelease?'
        required: true
        type: boolean
        default: false

jobs:
  build:
    runs-on: windows-latest
    continue-on-error: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.release_branch }}
          fetch-depth: 0
          fetch-tags: true
      
      - name: Create list of commits to cherrypick (based from master)
        id: list_commits
        shell: bash
        run: |
          git fetch origin ${{ github.event.inputs.feature_branch }}:${{ github.event.inputs.feature_branch }} || true
          git log master..${{ github.event.inputs.feature_branch }} --pretty=format:"%H" > commits_to_cherrypick.txt
      
      - name: Cherry-pick commits
        id: cherry_pick_commits
        shell: bash
        run: |
          if [ ! -s commits_to_cherrypick.txt ]; then
            echo "No commits to cherry-pick."
            exit 1
          fi
          while IFS= read -r commit; do
            git cherry-pick --no-commit "$commit" || {
              echo "Conflict occurred while cherry-picking commit $commit. Aborting cherry-pick."
              git cherry-pick --abort
              exit 1
            }
          done < commits_to_cherrypick.txt
          echo "Cherry-picked commits into integration/${{ github.event.inputs.feature_branch }}-to-${{ github.event.inputs.release_branch }}"

      - name: Cleanup before PR creation
        run: |
          rm -rf commits_to_cherrypick.txt

      - name: Create squashed pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ${{ github.event.inputs.release_branch }}
          branch: integration/${{ github.event.inputs.feature_branch }}-to-${{ github.event.inputs.release_branch }}
          title: "Squash cherrypick changes from ${{ github.event.inputs.feature_branch }} into ${{ github.event.inputs.release_branch }}"
          body: |
            This pull request was automatically created to squash cherrypick changes from `${{ github.event.inputs.feature_branch }}` into `${{ github.event.inputs.release_branch }}`.

            Please review the changes and resolve any conflicts if necessary.
          draft: false
