name: Run Tests on Master Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Checkout specific branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.release_branch }}
          fetch-depth: 0

      - name: Run Tests
        run: |
          make run-test

      - name: Dry run application building
        run: |
          make build
      
      - name: Check application build output
        run: |
          if not exist "dist\DrLogger.exe" (exit 1) else (echo "Build output exists.")