name: On Pull Request

on:
  pull_request:
    branches:
      - master
      - release/**

jobs:
  build-and-test:
    runs-on: windows-latest
    continue-on-error: false
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Checkout specific branch
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          make run-test

      - name: Build Application
        run: |
          make build

      - name: Upload Test Output
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: dist/DrLogger.exe